version: "3.9"
services:
 db:
   image: postgres:latest
   environment:
     POSTGRES_USER: user
     POSTGRES_PASSWORD: senha
     POSTGRES_DB: clientes
   ports:
     - "5432:5432"
   volumes:
     - pgdata:/var/lib/postgresql/data
 app:
   build: .
   depends_on:
     - db
   volumes:
     - .:/app
   environment:
     - POSTGRES_DB=clientes
     - POSTGRES_USER=user
     - POSTGRES_PASSWORD=senha
volumes:
 pgdata: